package com.jingda.guanli.dao;

import com.jingda.guanli.model.UserInfo;

import java.util.List;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated
     */
    int insertSelective(UserInfo record);

    List findAllUser();
    public void inserUser(String username,String password,String sex,String phone);

    public UserInfo selectUser(String username,String password);
    public UserInfo selectPerson(String username, String password,String sex,String phone);
}